# Generated by Django 3.0.5 on 2020-04-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('raca', models.CharField(max_length=45)),
                ('idade', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UsuarioAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_adocao', models.SmallIntegerField(choices=[('0', 'Não adotado'), ('1', 'Aguardando confirmação de adoção'), ('2', 'Adotado')], max_length=1)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfinder.Animais')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfinder.Usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='animais',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfinder.Usuarios'),
        ),
    ]
